TRUNCATE TABLE `property`;
ALTER TABLE `property` AUTO_INCREMENT = 1;

INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Semi-D', 'Eunos', 'fully furnished', 911064, 81, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Bungalow', 'Serangoon', 'near public transport', 469814, 93, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Maisonette', 'Hougang', 'newly renovated', 709762, 89, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy HDB', 'Vivo City', 'luxury finishings', 192115, 99, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Bungalow', 'Raffles Place', 'fully furnished', 1413173, 96, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Maisonette', 'Yishun', 'sea view', 575515, 79, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Semi-D', 'Novena', 'newly renovated', 1188985, 78, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Maisonette', 'Ang Mo Kio', 'near public transport', 1277152, 84, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious HDB', 'Woodlands', 'near public transport', 1812016, 95, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Semi-D', 'Woodlands', 'near public transport', 1855755, 89, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Loft', 'Raffles Place', 'near public transport', 1404913, 100, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Condo', 'Farrer Park', 'fully furnished', 468257, 86, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Semi-D', 'Jurong East', 'newly renovated', 1998617, 76, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Bungalow', 'Marine Parade', 'newly renovated', 846631, 91, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Condo', 'Ang Mo Kio', 'with swimming pool', 1640719, 83, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Maisonette', 'Raffles Place', 'near public transport', 1358627, 98, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Bungalow', 'Vivo City', 'near public transport', 462677, 92, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Loft', 'Woodlands', 'near public transport', 937753, 95, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Loft', 'Tampines', 'sea view', 881747, 94, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Bungalow', 'Tampines', 'newly renovated', 914200, 98, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming HDB', 'Serangoon', 'near public transport', 1286186, 88, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Bungalow', 'Lembing', 'luxury finishings', 529340, 90, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Semi-D', 'Kallang', 'newly renovated', 1459340, 89, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Modern HDB', 'Queenstown', 'near public transport', 548945, 94, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Condo', 'Farrer Park', 'urgent sale', 637710, 78, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Condo', 'Bedok', 'pet-friendly', 255557, 83, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Loft', 'Novena', 'with swimming pool', 1278878, 77, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Semi-D', 'Ang Mo Kio', 'near public transport', 425792, 82, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Maisonette', 'Yishun', 'newly renovated', 963904, 99, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Condo', 'Farrer Park', 'near public transport', 1796673, 80, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Loft', 'Jurong East', 'urgent sale', 390291, 99, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious HDB', 'Geylang', 'fully furnished', 1336889, 79, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury HDB', 'Vivo City', 'with swimming pool', 527138, 96, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Loft', 'Ang Mo Kio', 'fully furnished', 759670, 96, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy HDB', 'Lembing', 'urgent sale', 346156, 91, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Condo', 'Orchard', 'near public transport', 1796991, 92, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Loft', 'Hougang', 'urgent sale', 1985095, 97, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury HDB', 'Zion', 'fully furnished', 1697857, 94, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Maisonette', 'Vivo City', 'urgent sale', 1153368, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming HDB', 'Jurong East', 'near public transport', 845849, 83, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Modern Condo', 'Yishun', 'urgent sale', 1476851, 80, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Maisonette', 'Zion', 'urgent sale', 1182496, 80, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Maisonette', 'Hougang', 'urgent sale', 1099136, 93, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Semi-D', 'Geylang', 'near public transport', 1395970, 95, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Loft', 'Woodlands', 'newly renovated', 1743481, 98, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Loft', 'Pasir Ris', 'luxury finishings', 733709, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Condo', 'Tampines', 'sea view', 504330, 78, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic HDB', 'Raffles Place', 'urgent sale', 1952763, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Semi-D', 'Dover', 'luxury finishings', 1244263, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Semi-D', 'Vivo City', 'sea view', 1440183, 95, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Semi-D', 'Geylang', 'luxury finishings', 1325733, 100, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming HDB', 'Orchard', 'newly renovated', 1277234, 76, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Bungalow', 'Vivo City', 'urgent sale', 955488, 82, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Loft', 'Queenstown', 'fully furnished', 107189, 81, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious HDB', 'Orchard', 'with swimming pool', 145034, 100, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Bungalow', 'Tampines', 'urgent sale', 1707815, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Condo', 'Raffles Place', 'luxury finishings', 253975, 96, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Bungalow', 'Ubi', 'sea view', 1326956, 88, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic HDB', 'Hougang', 'newly renovated', 1265620, 81, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant HDB', 'Vivo City', 'sea view', 1288723, 83, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Condo', 'Dover', 'sea view', 1240413, 84, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious HDB', 'Pasir Ris', 'pet-friendly', 1818774, 86, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Maisonette', 'Hougang', 'with swimming pool', 1055656, 87, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Bungalow', 'Vivo City', 'luxury finishings', 766449, 80, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Condo', 'Pasir Ris', 'urgent sale', 1365741, 88, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Loft', 'Woodlands', 'luxury finishings', 1074568, 93, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Modern Bungalow', 'Geylang', 'with swimming pool', 1607538, 92, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Semi-D', 'Woodlands', 'fully furnished', 1318238, 76, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Bungalow', 'Clementi', 'pet-friendly', 636984, 90, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Modern Loft', 'Yishun', 'with swimming pool', 954467, 98, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Semi-D', 'Geylang', 'newly renovated', 1018479, 92, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Bungalow', 'Yishun', 'near public transport', 1223085, 85, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Bungalow', 'Pasir Ris', 'newly renovated', 840897, 76, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Maisonette', 'Novena', 'fully furnished', 737503, 76, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Maisonette', 'Ubi', 'luxury finishings', 777962, 90, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant HDB', 'Hougang', 'sea view', 373465, 85, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Semi-D', 'Marine Parade', 'newly renovated', 111505, 80, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Bungalow', 'Novena', 'sea view', 1294641, 83, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Maisonette', 'Orchard', 'with swimming pool', 551497, 85, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Loft', 'Zion', 'pet-friendly', 1024338, 89, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Semi-D', 'Farrer Park', 'luxury finishings', 197808, 76, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Loft', 'Yishun', 'with swimming pool', 918110, 88, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Maisonette', 'Marine Parade', 'fully furnished', 994454, 87, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Modern Semi-D', 'Yishun', 'urgent sale', 222771, 96, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Semi-D', 'Novena', 'with swimming pool', 1695376, 95, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Bungalow', 'Dover', 'newly renovated', 646827, 78, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Condo', 'Geylang', 'fully furnished', 1421834, 96, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Condo', 'Clementi', 'near public transport', 714020, 97, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Semi-D', 'Ubi', 'urgent sale', 978185, 79, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Luxury Bungalow', 'Raffles Place', 'with swimming pool', 999337, 83, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Loft', 'Novena', 'pet-friendly', 110166, 86, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Maisonette', 'Vivo City', 'fully furnished', 1792799, 97, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Loft', 'Bedok', 'urgent sale', 927354, 95, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Spacious Maisonette', 'Queenstown', 'newly renovated', 1205177, 94, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Cozy Bungalow', 'Yishun', 'near public transport', 738556, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Semi-D', 'Woodlands', 'pet-friendly', 1384350, 90, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Condo', 'Hougang', 'newly renovated', 1651740, 81, 1);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Elegant Semi-D', 'Woodlands', 'luxury finishings', 368373, 79, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Charming Loft', 'Marine Parade', 'with swimming pool', 1820453, 82, 0);
INSERT INTO `property` (name, location, info, price, sellerID, saleStatus) VALUES ('Rustic Maisonette', 'Farrer Park', 'sea view', 619749, 91, 1);