TRUNCATE TABLE `agent_reviews`;
ALTER TABLE `agent_reviews` AUTO_INCREMENT = 1;

INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (74, 3, 35, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (89, 4, 28, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (68, 3, 43, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (89, 4, 34, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (64, 3, 34, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (68, 3, 43, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (59, 3, 35, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (87, 4, 31, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (61, 3, 49, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (62, 3, 39, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (97, 4, 50, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (81, 4, 27, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (73, 3, 44, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (94, 4, 47, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (82, 4, 45, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (66, 3, 41, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (100, 4, 43, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (65, 3, 28, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (80, 4, 44, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (53, 3, 46, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (99, 4, 50, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (76, 4, 43, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (97, 4, 28, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (90, 4, 32, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (86, 4, 39, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (62, 3, 49, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (85, 4, 50, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (82, 4, 30, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (70, 3, 37, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (99, 4, 41, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (84, 4, 47, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (63, 3, 47, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (63, 3, 41, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (100, 4, 32, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (56, 3, 48, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (94, 4, 28, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (59, 3, 49, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (55, 3, 27, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (62, 3, 49, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (55, 3, 43, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (61, 3, 44, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (71, 3, 34, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (56, 3, 28, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (60, 3, 35, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (53, 3, 27, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (91, 4, 48, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (51, 3, 35, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (70, 3, 39, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (69, 3, 32, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (51, 3, 44, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (72, 3, 28, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (83, 4, 39, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (63, 3, 39, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (88, 4, 41, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (54, 3, 50, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (60, 3, 29, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (71, 3, 38, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (61, 3, 30, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (56, 3, 35, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (94, 4, 30, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (51, 3, 26, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (73, 3, 34, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (67, 3, 35, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (66, 3, 37, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (85, 4, 34, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (57, 3, 50, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (95, 4, 31, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (77, 4, 49, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (67, 3, 29, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (88, 4, 42, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (57, 3, 42, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (77, 4, 37, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (78, 4, 50, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (96, 4, 43, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (67, 3, 27, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (69, 3, 26, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (56, 3, 32, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (54, 3, 42, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (72, 3, 30, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (73, 3, 31, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (99, 4, 39, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (98, 4, 40, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (68, 3, 36, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (72, 3, 30, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (75, 3, 27, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (52, 3, 37, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (62, 3, 26, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (56, 3, 46, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (58, 3, 45, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (85, 4, 28, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (76, 4, 43, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (88, 4, 38, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (55, 3, 26, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (71, 3, 44, 'Great experience, will use again.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (66, 3, 42, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (59, 3, 49, 'Not satisfied with the service.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (81, 4, 33, 'Very professional and helpful.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (98, 4, 36, 'Excellent service, highly recommended!');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (66, 3, 50, 'Agent was very knowledgeable and responsive.');
INSERT INTO `agent_reviews` (reviewerID, reviewerType, agentID, review) VALUES (77, 4, 43, 'Very professional and helpful.');
